init redux example
feature-sliced/examples pull request #19
Opened 2022-07-20 07:52 UTC by EvgenyParomov

Добавление примера написанного на redux, redux-tookit
По большей части это копия примера на effector но все модели переписаны на redux

Главная идея, как сохранить модульность и инкапсуляцию при работе с единым redux состоянием

2022-07-21 11:26 UTC, Rin-Akaia-eth requested changes

2022-07-21 11:26 UTC, Rin-Akaia-eth commented on todo-app-redux/src/app/styles/normalize-antd.scss
> +// Лоадер на весь контейнер
I'm not sure we need this comment here at all, but if you think we do, please use English

2022-07-21 11:26 UTC, Rin-Akaia-eth commented on todo-app-redux/src/entities/task/model/index.ts
> +// Разбиваем на submodels
-> English

2022-07-21 11:26 UTC, Rin-Akaia-eth commented on todo-app-redux/src/entities/task/model/tasks.ts
> +// Этот файл можно разделить на меньшие файлы при увеличении в нём колличество логики,
-> English

2022-07-21 11:26 UTC, Rin-Akaia-eth commented on todo-app-redux/src/entities/task/model/tasks.ts
> +// Повторение структуры папок упрощает навигацию и защищает от конфликтов
-> English

2022-07-21 11:26 UTC, Rin-Akaia-eth commented on todo-app-redux/src/entities/task/model/tasks.ts
> +// Мы определяем только публичные экшоны, мы защищаем инварианты нашего состояния
-> English

2022-07-21 11:26 UTC, Rin-Akaia-eth commented on todo-app-redux/src/entities/task/model/tasks.ts
> +// Мы определяем только публичные селекторы, таким образом мы скрываем структуру данных нашего состояния
-> English

2022-07-21 11:26 UTC, Rin-Akaia-eth commented on todo-app-redux/src/entities/task/model/tasks.ts
> +// Мы экспортируем структуру редьюссеров целиком, таким образом reducerPath остаётся приватным
-> English

2022-07-21 11:26 UTC, Rin-Akaia-eth commented on todo-app-redux/src/entities/task/ui/task-row/index.tsx
> +        // Можно смело использовать classnames и аналоги
```suggestion
```

2022-07-21 11:26 UTC, Rin-Akaia-eth commented on todo-app-redux/src/entities/task/ui/task-row/index.tsx
> +import cn from "classnames"; // Можно смело использовать аналоги
```suggestion
import cn from "classnames";
```

2022-07-21 11:26 UTC, Rin-Akaia-eth commented on todo-app-redux/src/entities/task/ui/task-card/index.tsx
> +            // Можно обработать и получше при желании
```suggestion
```

2022-07-21 11:26 UTC, Rin-Akaia-eth commented on todo-app-redux/src/entities/task/ui/task-card/index.tsx
> +    // Можно обработать и получше при желании
```suggestion
```

2022-07-21 11:26 UTC, Rin-Akaia-eth commented on todo-app-redux/src/entities/task/ui/task-row/styles.module.scss
> +    // Можно и получше подобрать стили
```suggestion
```

2022-07-21 11:26 UTC, Rin-Akaia-eth commented on todo-app-redux/src/entities/task/model/tasks.ts
> +// selecotrs
```suggestion
// selectors
```

2022-07-21 11:26 UTC, Rin-Akaia-eth commented on todo-app-redux/src/features/tasks-filters/config.ts
> +// Описываем здесь датасет фильтров "Закрытые" / "Открытые" и т.п.
-> English

2022-07-21 11:26 UTC, Rin-Akaia-eth commented on todo-app-redux/src/pages/index.tsx
> +// Либо использовать @loadable/component, в рамках туториала - некритично
```suggestion
```

2022-07-21 11:26 UTC, Rin-Akaia-eth commented on todo-app-redux/src/shared/api/typicode/base.ts
> +// Потенциально, можно передавать accessToken
-> English

2022-07-21 11:26 UTC, Rin-Akaia-eth commented on todo-app-redux/src/shared/config/index.ts
> + * Модуль инициализации env-переменных
Please translate all the comments in this file to English

2022-07-21 11:26 UTC, Rin-Akaia-eth commented on todo-app-redux/src/shared/lib/redux-std/root-state.ts
> +// RootState намеренно не типизирован что бы скрыть структуру состояния
Please translate all the comments in this file to English

2022-07-21 11:26 UTC, Rin-Akaia-eth commented on todo-app-redux/src/shared/lib/redux-std/use-action.ts
> +  // Можно написать более строгие типы если нужно
-> English

2022-07-21 11:26 UTC, Rin-Akaia-eth commented on todo-app-redux/src/shared/lib/redux-std/use-action.ts
> +export const useAction = <A extends any[]>(
Replace `any` with `unknown` everywhere

2022-07-21 11:26 UTC, Rin-Akaia-eth commented on todo-app-redux/tsconfig.json
> +    "target": "es5",
I recommend using `"es6"` target

2022-11-23 07:35 UTC, nnsense91 commented on todo-app-redux/src/features/tasks-filters/model/task-filters.slice.ts
> +const reducerPatch = "features/task-filters";
reducerPath

2024-06-24 22:00 UTC, illright commented
Seems like this PR has gone stale, I'll close it

2024-06-24 22:00 UTC, closed without merging